print("---------------------------")
print("ABC Shop VAT INVOICE")
print("---------------------------")
print("Water      x 1 : 10   THB")
print("Banana     x 1 : 15   THB")
print("Coke       x 1 : 13   THB")
print("Cola       x 1 : 15   THB")
print("PotatoChip x 1 : 20   THB")
print("Benmore    x 1 : 25   THB")
print("Cupcake    x 3 : 105  THB")
print("Apple      x 5 : 50   THB")

print("---------------------------")
print("Total          : 253  THB")

